name: notion2quizpdf
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - anaconda::beautifulsoup4=4.11.1
  - anaconda::tqdm=4.64.1
  - conda-forge::selenium=4.8.2=pyhd8ed1ab_0
  - conda-forge::python-chromedriver-binary<=111.0.5563.111
  - conda-forge::pypdf2=2.11.1
  - pip:
      - git+https://github.com/KYasuda516/python-mylib.git
