# Copyright (c) 2023 Kanta Yasuda (GitHub: @kyasuda516)
# This software is released under the MIT License, see LICENSE.

name: notion2quiz-pdf-env
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - anaconda::beautifulsoup4=4.11.1
  - anaconda::tqdm=4.64.1
  - conda-forge::selenium=4.8.2
  - conda-forge::python-chromedriver-binary<=111.0.5563.111
  - conda-forge::pypdf2=2.11.1
  - pip:
      - git+https://github.com/kyasuda516/python-mylib.git
